08/16/2022 02:58:52 PM: INFO - Made app
08/16/2022 02:58:52 PM: DEBUG - Using proactor: IocpProactor
08/16/2022 02:58:56 PM: INFO - 304 GET / (::1) 4.01ms
08/16/2022 02:58:56 PM: INFO - 101 GET /ws (::1) 0.00ms
08/16/2022 02:58:56 PM: INFO - WebSocket opened
08/16/2022 02:58:59 PM: DEBUG - TEC is True
08/16/2022 02:59:03 PM: DEBUG - Laser is True
08/16/2022 03:00:06 PM: DEBUG - Laser is False
08/16/2022 03:00:07 PM: DEBUG - TEC is False
08/16/2022 03:00:38 PM: ERROR - Uncaught exception GET /ws (::1)
HTTPServerRequest(protocol='http', host='localhost:8042', method='GET', uri='/ws', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "C:\Users\nickb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tornado\websocket.py", line 647, in _run_callback
    result = callback(*args, **kwargs)
  File "C:\Users\nickb\Documents\GitHub\PorTel-Beacon-sw\Python_GUI\PorTel_Pi_Code\main.py", line 71, in on_message
    self.controller.GeneralUpdate()
  File "C:\Users\nickb\Documents\GitHub\PorTel-Beacon-sw\Python_GUI\PorTel_Pi_Code\Controller.py", line 187, in GeneralUpdate
    res = self.microcontroller.transferData(toSend)
  File "C:\Users\nickb\Documents\GitHub\PorTel-Beacon-sw\Python_GUI\PorTel_Pi_Code\Controller.py", line 305, in transferData
    self._send_packet(struct.pack(PACKET_SEND_FORMAT,*mySend)) #Unpack tuple and pack into struct and serialize
  File "C:\Users\nickb\Documents\GitHub\PorTel-Beacon-sw\Python_GUI\PorTel_Pi_Code\Controller.py", line 261, in _send_packet
    self._serial.write(bytearray(encoded) + b'\x00')
  File "C:\Users\nickb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\serial\serialwin32.py", line 317, in write
    raise SerialException("WriteFile failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: WriteFile failed (PermissionError(13, 'The device does not recognize the command.', None, 22))
